export const queryKeys = {
    ADMIN: 'admin',
    FASILITATOR: 'fasilitator',
    PJ_GRUP: 'pj_grup',
    GRUP_DAMPINGAN: 'grup_dampingan',
    ANGGOTA_GRUP: 'anggota_grup',
    KEGIATAN: 'kegiatan',
    BIDANG: 'bidang',
    LEVEL_KEGIATAN: 'level_kegiatan',
    PROFIL: 'profil',
    LOG_AKTIVITAS: 'log_aktivitas',
    PANDUAN: 'panduan',
    RBAC: 'rbac',
    DASHBOARD_FASILITATOR: 'dashboard_fasilitator',
    DASHBOARD_ADMIN: 'dashboard_admin',
};
